[package]
name = "firmware"
version = "0.1.0"
authors = ["Fabrice Desré <fabrice@desre.org>"]

[dependencies]
cc3200-sys = { path = "cc3200-sys" }
freertos_alloc = { path = "freertos_alloc" }
freertos_rs = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
# Note: gcc has some codegen issues with -O3
opt-level = "s"
debug = true
panic = "abort"
