[package]
name = "firmware"
version = "0.1.0"
authors = ["Fabrice Desré <fabrice@desre.org>"]

[dependencies]
cc3200-sys = { path = "cc3200-sys" }
freertos_rs = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
