[package]
name = "cc3200-sys"
version = "0.1.0"
authors = ["Dave Hylands <dhylands@gmail.com>"]
build = "build.rs"

[build-dependencies]
common-build = { path = "../common-build" }

[dependencies]
log = { version = "0.3", default-features = false }
